version: "3"
services:
  eurekaserver:
    build: .
    ports:
      - "8761:8080"
    pull_policy: always
    networks:
      - eureka_network

  apigateway:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver
    networks:
      - eureka_network

  userservice:
    build: .
    ports:
      - "8181:8080"
    depends_on:
      - apigateway
    networks:
      - eureka_network

  orderservice:
    build: .
    ports:
      - "8282:8080"
    depends_on:
      - eurekaserver
    networks:
      - eureka_network

  notificationservice:
    build: .
    ports:
      - "8383:8080"
    depends_on:
      - eurekaserver
    networks:
      - eureka_network

  authenticationservice:
    build: .
    ports:
      - "8484:8080"
    depends_on:
      - eurekaserver
    networks:
      - eureka_network

networks:
  eureka_network:
    driver: bridge
