spring:
  application:
    name: order-service
  zipkin:
    base-url: http://zipkin:9411/

server:
  port: 8080
eureka:
  instance:
    hostname: eurekaserver
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

security:
  oauth2:
    resource:
      token-info-uri: http://authentication-service/oauth/check_token
    client:
      client-id: javadeveloperzone
      client-secret: secret

feign:
  circuitbreaker:
    enabled: true
