spring:
  application:
    name: user-service
  zipkin:
    base-url: http://zipkin:9411/

server:
  port: 8080
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

security:
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://authentication-service:8080/oauth/check_token
    client:
      client-id: javadeveloperzone
      client-secret: secret
